/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_timeTool_IdleJob */

#ifndef _Included_com_timeTool_IdleJob
#define _Included_com_timeTool_IdleJob
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_timeTool_IdleJob
 * Method:    getIdleTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_timeTool_IdleJob_getIdleTime
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
